# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'param_panel.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1037, 890)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("color: rgb(242, 242, 242);\n"
"background-color: rgb(38, 38, 38);")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbSubjects = QtWidgets.QLabel(Dialog)
        self.lbSubjects.setObjectName("lbSubjects")
        self.verticalLayout_4.addWidget(self.lbSubjects)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbSelectAllSubjects = QtWidgets.QPushButton(Dialog)
        self.pbSelectAllSubjects.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.pbSelectAllSubjects.setObjectName("pbSelectAllSubjects")
        self.horizontalLayout_3.addWidget(self.pbSelectAllSubjects)
        self.pbUnselectAllSubjects = QtWidgets.QPushButton(Dialog)
        self.pbUnselectAllSubjects.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.pbUnselectAllSubjects.setObjectName("pbUnselectAllSubjects")
        self.horizontalLayout_3.addWidget(self.pbUnselectAllSubjects)
        self.pbReverseSubjectsSelection = QtWidgets.QPushButton(Dialog)
        self.pbReverseSubjectsSelection.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.pbReverseSubjectsSelection.setObjectName("pbReverseSubjectsSelection")
        self.horizontalLayout_3.addWidget(self.pbReverseSubjectsSelection)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.lwSubjects = QtWidgets.QListWidget(Dialog)
        self.lwSubjects.setStyleSheet("QListWidget::item {\n"
"    background-color: rgb(38, 38, 38);\n"
"    color: rgb(242, 242, 242);\n"
"    border-color: rgb(242, 242, 242);\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(89, 89, 89);\n"
"    color: rgb(242, 242, 242);\n"
" }")
        self.lwSubjects.setObjectName("lwSubjects")
        self.verticalLayout_4.addWidget(self.lwSubjects)
        self.lbBehaviors = QtWidgets.QLabel(Dialog)
        self.lbBehaviors.setObjectName("lbBehaviors")
        self.verticalLayout_4.addWidget(self.lbBehaviors)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbSelectAllBehaviors = QtWidgets.QPushButton(Dialog)
        self.pbSelectAllBehaviors.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.pbSelectAllBehaviors.setObjectName("pbSelectAllBehaviors")
        self.horizontalLayout_4.addWidget(self.pbSelectAllBehaviors)
        self.pbUnselectAllBehaviors = QtWidgets.QPushButton(Dialog)
        self.pbUnselectAllBehaviors.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.pbUnselectAllBehaviors.setObjectName("pbUnselectAllBehaviors")
        self.horizontalLayout_4.addWidget(self.pbUnselectAllBehaviors)
        self.pbReverseBehaviorsSelection = QtWidgets.QPushButton(Dialog)
        self.pbReverseBehaviorsSelection.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.pbReverseBehaviorsSelection.setObjectName("pbReverseBehaviorsSelection")
        self.horizontalLayout_4.addWidget(self.pbReverseBehaviorsSelection)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.lwBehaviors = QtWidgets.QListWidget(Dialog)
        self.lwBehaviors.setStyleSheet("QListWidget::item {\n"
"    background-color: rgb(38, 38, 38);\n"
"    color: rgb(242, 242, 242);\n"
"    border-color: rgb(242, 242, 242);\n"
"}\n"
"QListWidget::item:selected {\n"
"    background-color: rgb(89, 89, 89);\n"
"    color: rgb(242, 242, 242);\n"
" }")
        self.lwBehaviors.setObjectName("lwBehaviors")
        self.verticalLayout_4.addWidget(self.lwBehaviors)
        self.cbIncludeModifiers = QtWidgets.QCheckBox(Dialog)
        self.cbIncludeModifiers.setObjectName("cbIncludeModifiers")
        self.verticalLayout_4.addWidget(self.cbIncludeModifiers)
        self.cbExcludeBehaviors = QtWidgets.QCheckBox(Dialog)
        self.cbExcludeBehaviors.setObjectName("cbExcludeBehaviors")
        self.verticalLayout_4.addWidget(self.cbExcludeBehaviors)
        self.frm_time = QtWidgets.QFrame(Dialog)
        self.frm_time.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_time.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_time.setObjectName("frm_time")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frm_time)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.rb_full = QtWidgets.QRadioButton(self.frm_time)
        self.rb_full.setChecked(True)
        self.rb_full.setObjectName("rb_full")
        self.horizontalLayout_5.addWidget(self.rb_full)
        self.rb_interval = QtWidgets.QRadioButton(self.frm_time)
        self.rb_interval.setObjectName("rb_interval")
        self.horizontalLayout_5.addWidget(self.rb_interval)
        self.rb_limit = QtWidgets.QRadioButton(self.frm_time)
        self.rb_limit.setObjectName("rb_limit")
        self.horizontalLayout_5.addWidget(self.rb_limit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.frm_time_interval = QtWidgets.QFrame(self.frm_time)
        self.frm_time_interval.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_time_interval.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_time_interval.setObjectName("frm_time_interval")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frm_time_interval)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frm_time_interval)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbStartTime = QtWidgets.QLabel(self.frm_time_interval)
        self.lbStartTime.setObjectName("lbStartTime")
        self.horizontalLayout.addWidget(self.lbStartTime)
        self.teStartTime = QtWidgets.QTimeEdit(self.frm_time_interval)
        self.teStartTime.setObjectName("teStartTime")
        self.horizontalLayout.addWidget(self.teStartTime)
        self.dsbStartTime = QtWidgets.QDoubleSpinBox(self.frm_time_interval)
        self.dsbStartTime.setDecimals(3)
        self.dsbStartTime.setMaximum(1000000.0)
        self.dsbStartTime.setObjectName("dsbStartTime")
        self.horizontalLayout.addWidget(self.dsbStartTime)
        self.lbEndTime = QtWidgets.QLabel(self.frm_time_interval)
        self.lbEndTime.setObjectName("lbEndTime")
        self.horizontalLayout.addWidget(self.lbEndTime)
        self.teEndTime = QtWidgets.QTimeEdit(self.frm_time_interval)
        self.teEndTime.setObjectName("teEndTime")
        self.horizontalLayout.addWidget(self.teEndTime)
        self.dsbEndTime = QtWidgets.QDoubleSpinBox(self.frm_time_interval)
        self.dsbEndTime.setDecimals(3)
        self.dsbEndTime.setMaximum(1000000.0)
        self.dsbEndTime.setObjectName("dsbEndTime")
        self.horizontalLayout.addWidget(self.dsbEndTime)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addWidget(self.frm_time_interval)
        self.verticalLayout_4.addWidget(self.frm_time)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.pbCancel = QtWidgets.QPushButton(Dialog)
        self.pbCancel.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.pbCancel.setObjectName("pbCancel")
        self.horizontalLayout_2.addWidget(self.pbCancel)
        self.pbOK = QtWidgets.QPushButton(Dialog)
        self.pbOK.setStyleSheet("background-color: rgb(13, 13, 13);")
        self.pbOK.setObjectName("pbOK")
        self.horizontalLayout_2.addWidget(self.pbOK)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Parametros"))
        self.lbSubjects.setText(_translate("Dialog", "Assuntos"))
        self.pbSelectAllSubjects.setText(_translate("Dialog", "Selecionar tudo"))
        self.pbUnselectAllSubjects.setText(_translate("Dialog", "Desfazer tudo"))
        self.pbReverseSubjectsSelection.setText(_translate("Dialog", "Reverter seleção"))
        self.lbBehaviors.setText(_translate("Dialog", "Comportamentos"))
        self.pbSelectAllBehaviors.setText(_translate("Dialog", "Selecionar tudo"))
        self.pbUnselectAllBehaviors.setText(_translate("Dialog", "Desfazer tudo"))
        self.pbReverseBehaviorsSelection.setText(_translate("Dialog", "Reverter seleção"))
        self.cbIncludeModifiers.setText(_translate("Dialog", "Incluir modificadores"))
        self.cbExcludeBehaviors.setText(_translate("Dialog", "Excluir comportamentos sem eventos"))
        self.rb_full.setText(_translate("Dialog", "Observação(ões) completa(s)"))
        self.rb_interval.setText(_translate("Dialog", "Limite para intervalo de tempo"))
        self.rb_limit.setText(_translate("Dialog", "Limite para eventos observados"))
        self.label.setText(_translate("Dialog", "Intervalo de tempo"))
        self.lbStartTime.setText(_translate("Dialog", "Início"))
        self.teStartTime.setDisplayFormat(_translate("Dialog", "hh:mm:ss.zzz"))
        self.lbEndTime.setText(_translate("Dialog", "Fim"))
        self.teEndTime.setDisplayFormat(_translate("Dialog", "hh:mm:ss.zzz"))
        self.pbCancel.setText(_translate("Dialog", "Cancel"))
        self.pbOK.setText(_translate("Dialog", "OK"))

